export const LOGIN = 'LOGIN';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const INSTRUCTOR_SIGNUP = 'INSTRUCTOR_SIGNUP';
export const INSTRUCTOR_SIGNUP_FAIL = 'INSTRUCTOR_SIGNUP_FAIL';
