export const LOGIN = 'LOGIN';
export const AUTHENTICATED = 'AUTHENTICATED';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const INSTRUCTOR_SIGNUP = 'INSTRUCTOR_SIGNUP';
export const INSTRUCTOR_SIGNUP_FAIL = 'INSTRUCTOR_SIGNUP_FAIL';
export const SOCKET = 'SOCKET';
export const SOCKET_ON = 'SOCKET_ON';
export const SOCKET_EMIT = 'SOCKET_EMIT';
export const START_SESSION = 'START_SESSION';
export const END_SESSION = 'END_SESSION';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const NEW_MESSAGE = 'NEW_MESSAGE';
export const GET_ALL_MESSAGES = 'GET_ALL_MESSAGES';
export const GET_ALL_QUESTIONS = 'GET_ALL_QUESTIONS';
export const GET_MY_PROFILE = 'GET_MY_PROFILE';

//about Forum
export const CREATE_POST = 'CREATE_POST';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REQUEST_POSTS_PENDING = 'REQUEST_POSTS_PENDING';
export const REQUEST_POSTS_SUCCESS = 'REQUEST_POSTS_SUCCESS';
export const REQUEST_POSTS_FAILED = 'REQUEST_POSTS_FAILED';
export const REQUEST_POSTDETAILS_PENDING = 'REQUEST_POSTDETAILS_PENDING';
export const REQUEST_POSTDETAILS_SUCCESS = 'REQUEST_POSTDETAILS_SUCCESS';
export const REQUEST_POSTDETAILS_FAILED = 'REQUEST_POSTDETAILS_FAILED';

export const REQUEST_MYPOSTS = 'REQUEST_MYPOSTS';
export const REQUEST_MYCOMMENTS = 'REQUEST_MYCOMMENTS';
